export const produkTable = {
  content: [
    {
      date: "12/04/2023",
      id: 1,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 2,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 3,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 4,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 5,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 6,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 7,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 8,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
  ],
  totalElements: 10,
  number: 0,
  size: 5,
};

export const opnameTable = {
  content: [
    {
      date: "12/04/2023",
      id: 1,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 2,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 3,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 4,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 5,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 6,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 7,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
    {
      date: "12/04/2023",
      id: 8,
      brand: "Asus",
      category: "Laptop",
      unit: "PCS",
      status: "IN - BUY",
      qty: 940,
      updatedby: "Gudang J90",
    },
  ],
  totalElements: 10,
  number: 0,
  size: 5,
};

export const mutasiTable = {
  content: [
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
  ],
  totalElements: 10,
  number: 0,
  size: 5,
};

export const returnTable = {
  content: [
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
    {
      tanggal: "20/11/2029",
      id: "RTN/0039",
      brand: "Sanex",
      jenis: "Kipas Angin",
      qty: "200 Pcs",
      updatedBy: "Gudang M23",
      status: true,
    },
  ],
  totalElements: 10,
  number: 0,
  size: 5,
};

export const listProdukTable = {
  content: [
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
    {
      id: 'LST/0219',
      brand: 'Miyako',
      jenis: 'Rice Cooker',
      supplier: 'PT. Sinar Jaya',
      hargaPcs: '120.000',
      hargaLusin: '1.440.000',
      hargaBox: '2.880.000',
      updatedBy: 'Gudang K24'
    },
  ],
  totalElements: 10,
  number: 0,
  size: 5
}