export const ListAdmin = [
  {
    id: 1,
    name: "Dashboard",
    navigate: "/dashboard",
    icon: "dashboard",
  },
  {
    id: 2,
    name: "Data Pengguna",
    navigate: "/user-data",
    icon: "admin_panel_settings",
  },
  {
    id: 3,
    name: "Data Toko",
    navigate: "/store-data",
    icon: "store",
  },
  {
    id: 4,
    name: "Role Pengguna",
    navigate: "/user-role",
    icon: "perm_contact_calendar",
  },
  {
    id: 5,
    name: "Peran",
    navigate: "/user-access",
    icon: "lock_person"
  },

];

export const ListUser = [
  {
    id: 1,
    label: "Dashboard",
    name: "DASHBOARD",
    icon: "dashboard",
    navigate: "/dashboard-user",
    expandable: false,
    children: [],
  },
  {
    id: 2,
    label: "Gudang",
    name: "GUDANG",
    icon: "warehouse",
    navigate: "",
    expandable: true,
    children: [
      {
        id: 2.1,
        label: "Data Produk",
        name: "DATA_PRODUK",
        icon: "webhook",
        navigate: "/gudang/data-produk",
      },
      {
        id: 2.2,
        label: "Mutasi & Return",
        name: "MUTASI",
        icon: "sync_alt",
        navigate: "/gudang/mutasi",
      },
      {
        id: 2.2,
        label: "List Produk",
        name: "LIST_PRODUK",
        icon: "widgets",
        navigate: "/gudang/list-produk",
      },
    ],
  },
  {
    id: 3,
    label: "Penjualan",
    name: "PENJUALAN",
    icon: "price_check",
    navigate: "",
    expandable: true,
    children: [
      {
        id: 3.1,
        label: "Penjualan",
        name: "PENJUALAN",
        icon: "receipt_long",
        navigate: "/penjualan/penjualan",
      },
      {
        id: 3.2,
        label: "Return Penjualan",
        name: "RETURN",
        icon: "settings_backup_restore",
        navigate: "/penjualan/return-penjualan",
      },
    ],
  },
  {
    id: 4,
    label: "Pembelian",
    name: "PEMBELIAN",
    icon: "add_shopping_cart",
    navigate: "",
    expandable: true,
    children: [
      {
        id: 4.1,
        label: "Pembelian",
        name: "PEMBELIAN",
        icon: "shopping_cart_checkout",
        navigate: "/pembelian/pembelian",
      },
      {
        id: 4.2,
        label: "Tracking",
        name: "TRACKING",
        icon: "track_changes",
        navigate: "/pembelian/tracking",
      },
    ],
  },
  {
    id: 5,
    label: "Akun",
    name: "AKUN",
    icon: "description",
    navigate: "/akun",
    expandable: false,
    children: [],
  },
  {
    id: 6,
    label: "Laporan",
    name: "LAPORAN",
    icon: "query_stats",
    navigate: "",
    expandable: true,
    children: [
      {
        id: 6.1,
        label: "Lap. Keuangan",
        name: "LAP_KEUANGAN",
        icon: "price_change",
        navigate: "/laporan/keuangan",
      },
      {
        id: 6.2,
        label: "Lap. Penjualan & Pembelian",
        name: "LAP_PENJUALAN",
        icon: "swap_vert",
        navigate: "/laporan/transaksi",
      },
      // {
      //   id: 6.2,
      //   label: "Kelola Kas & Bank",
      //   name: "LAP_BANK",
      //   icon: "account_balance",
      //   navigate: "/laporan/bank",
      // },
    ],
  },
  {
    id: 7,
    label: "Kontak",
    name: "KONTAK",
    icon: "contacts",
    navigate: "",
    expandable: true,
    children: [
      {
        id: 7.1,
        label: "Pelanggan",
        name: "PELANGGAN",
        icon: "shopping_bag",
        navigate: "/kontak/pelanggan",
      },
      {
        id: 7.2,
        label: "Supplier",
        name: "SUPPLIER",
        icon: "format_list_numbered",
        navigate: "/kontak/supplier",
      },
      {
        id: 7.3,
        label: "Ekspedisi",
        name: "EKSPEDISI",
        icon: "local_shipping",
        navigate: "/kontak/ekspedisi",
      },
      {
        id: 7.4,
        label: "Akun Bank",
        name: "BANKS",
        icon: "local_shipping",
        navigate: "/kontak/akun-bank",
      },
    ],
  },
  {
    id: 8,
    label: "Approval",
    name: "APPROVAL",
    icon: "approval",
    navigate: "",
    expandable: true,
    children: [
      {
        id: 8.1,
        label: "App. Gudang",
        name: "APV_GUDANG",
        icon: "warehouse",
        navigate: "/approval/gudang",
      },
      {
        id: 8.1,
        label: "App. Penjualan",
        name: "APV_PENJUALAN",
        icon: "price_check",
        navigate: "/approval/penjualan",
      },
      {
        id: 8.1,
        label: "App. Pembelian",
        name: "APV_PEMBELIAN",
        icon: "add_shopping_cart",
        navigate: "/approval/pembelian",
      },
    ],
  },
  {
    id: 9,
    label: "Pengaturan",
    name: "PENGATURAN",
    icon: "settings",
    navigate: "",
    expandable: true,
    children: [
      {
        id: 9.1,
        label: "Data Toko",
        name: "DATA_TOKO",
        icon: "local_convenience_store",
        navigate: "/settings/data-toko",
      },
      {
        id: 9.2,
        label: "Penomoran",
        name: "PENOMORAN",
        icon: "format_list_numbered",
        navigate: "/settings/penomoran",
      },
      {
        id: 9.3,
        label: "Profilku",
        name: "PROFIL",
        icon: "manage_accounts",
        navigate: "/settings/profilku",
      },
      {
        id: 9.4,
        label: "Peran",
        name: "PERAN",
        icon: "lock_open",
        navigate: "/settings/peran",
      },
    ],
  },
];
