export const approvalTable = {
  content: [
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
    {
      tanggal: "30/01/2023",
      no: "KLM/1029",
      jenisBarang: "Lampu Neon",
      jumlah: 34,
      asal: "Gudang A",
      tujuan: "Gudang Z",
      jenisMutasi: "OUT - CROSS",
      updatedBy: "Gudang A34",
      status: true,
    },
  ],
  totalElements: 10,
  number: 0,
  size: 5,
};

export const penjualanDataTable = {
  content: [
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
    {
      tanggal: "30/01/2023",
      id: "KLM/1029",
      pelanggan: "Riyanto",
      barang: "Dispenser 300watt",
      jumlah: "50",
      jenis: "Retail",
      status: "Pending",
      updatedBy: "Gudang A34",
    },
  ],
  totalElements: 10,
  number: 0,
  size: 5,
};

export const pembelianDataTable = {
  content: [
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
    {
      tanggal: "21/12/2023",
      id: "SKU/012",
      brand: "Cosmos",
      kategori: "Kipas Angin",
      supplier: "PT. Jaya Abadi",
      tempo: 1200,
      tagihan: 0,
      total: "240.000",
      status: "Menunggu Persetujuan",
      updatedby: "Gudang A55",
    },
  ],
  totalElements: 10,
  number: 0,
  size: 5,
};
